name: dmt
description: dmt
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+4
  http: ^0.13.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  permission_handler: ^10.0.2
  flutter_blue_plus: ^1.3.1
  signature: ^5.2.1
  dotted_border: ^2.0.0+2
  file_picker: ^5.2.1
  path_provider: 2.0.9
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:

  uses-material-design: true
  assets:
    - assets/images/

